// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
    id: string;
    createdAt: number;
};

export type Entity<T> = {
    [K in keyof T]: T[K];
} & BaseEntity;

export type User = Entity<{
    id: number;
    firstName: string;
    lastName: string;
    middle_name: string;
    email: string;
}>;

export type LoginResponse = {
    access_token: string;
    token_type: string;
};

export type AuthResponse = {
    access_token: string;
    jwt: string;
    user: User;
};
